version: '3.1'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passrestfull
      - MYSQL_DATABASE=restfull-mysql
  app:
    image:phpmyadmin/phpmyadmin:lastest
  links:
    - db
  ports:
    - 80:80
  environment:
    - PMA_ARBITRARY=1    